name: coord2vec
channels:
- pytorch
- h2oai
- conda-forge
- defaults

dependencies:
# Core scientific python
- numpy
- matplotlib
- python>=3.6
- seaborn
- pip
- scikit-learn
- scikit-image
- h2o  # install via conda install -c h2oai h2o
- pytest

# Deep Learning
- pytorch=1.1.0
- torchvision
- cudatoolkit
- ignite  # from the pytorch channel

# Spatial packages
#- rasterstats
- geopy
#- cartopy
- geopandas
#- rasterio
#- contextily
#- pysal
- pyproj
- folium
- gdal
- libgdal
#- kealib
#- geocoder
- geojson
- psycopg2

# Jupyter Environment
- autopep8
- notebook
- ipython
- jupyter_contrib_nbextensions
- jupyterlab
- jupyter
- nb_conda

# Web app / visualization
- flask
- bokeh
- holoviews

- pip:
    - nbclean
    - imageio
    - tqdm
    - auto-tqdm
    - staticmap
    - pathos
    - torchsummary
    - tb-nightly  # for tensorboard
    - openrouteservice
    - xlrd  # missing from docker
