name: coord2vec
channels:
- conda-forge
- defaults

dependencies:
# Core scientific python
- numpy
- matplotlib
- python>=3.6
- seaborn
- tqdm
- pip
- scikit-learn
- scikit-image
- h2oai::h2o

# Deep Learning
- pytorch
- torchvision
- cudatoolkit=9.0

# Spatial packages
- rasterstats
- geopy
- cartopy
- geopandas
- rasterio
- contextily
- pysal
- pyproj
- folium
- gdal
- libgdal
- kealib
- geocoder
- geojson
- psycopg2

# Jupyter Environment
- autopep8
- notebook
- ipython
- jupyter_contrib_nbextensions
- jupyterlab
- jupyter
- nb_conda

- pip:
    - nbclean
    - mapboxgl
    - hydrofunctions
    - imageio
    - staticmap
    - pathos
